include: package:lint/analysis_options_package.yaml
linter:
  rules:
    # Disable
    avoid_positional_boolean_parameters: false
    unsafe_html: false
    avoid_web_libraries_in_flutter: false
    avoid_classes_with_only_static_members: false
    directives_ordering: false
    no_leading_underscores_for_local_identifiers: false
    require_trailing_commas: false,
