name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  pointer_interceptor: ^0.9.3+6
  uuid: ^3.0.7
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
